import React from "react";
import logo from "./logo.svg";
import "./App.css";

function App() {
  const arr = [
    {
      id: "1",
      name: "Small Metal Chair",
      price: "743.00",
      desc: "Table",
      image: "http://lorempixel.com/640/480/fashion",
    },
    {
      id: "2",
      name: "Fantastic Frozen Shirt",
      price: "792.00",
      desc: "Tuna",
      image: "http://lorempixel.com/640/480/nature",
    },
    {
      id: "3",
      name: "Fantastic Granite Pizza",
      price: "901.00",
      desc: "Shirt",
      image: "http://lorempixel.com/640/480/fashion",
    },
    {
      id: "4",
      name: "Awesome Cotton Pants",
      price: "687.00",
      desc: "Sausages",
      image: "http://lorempixel.com/640/480/nature",
    },
    {
      id: "5",
      name: "Tasty Plastic Pizza",
      price: "998.00",
      desc: "Computer",
      image: "http://lorempixel.com/640/480/fashion",
    },
    {
      id: "6",
      name: "Ergonomic Soft Salad",
      price: "889.00",
      desc: "Cheese",
      image: "http://lorempixel.com/640/480/business",
    },
    {
      id: "7",
      name: "Ergonomic Frozen Shoes",
      price: "999.00",
      desc: "Hat",
      image: "http://lorempixel.com/640/480/business",
    },
    {
      id: "8",
      name: "Practical Rubber Pizza",
      price: "280.00",
      desc: "Car",
      image: "http://lorempixel.com/640/480/cats",
    },
    {
      id: "9",
      name: "Handmade Frozen Soap",
      price: "892.00",
      desc: "Hat",
      image: "http://lorempixel.com/640/480/nightlife",
    },
    {
      id: "10",
      name: "Awesome Wooden Gloves",
      price: "886.00",
      desc: "Computer",
      image: "http://lorempixel.com/640/480/abstract",
    },
    {
      id: "11",
      name: "Small Cotton Chicken",
      price: "362.00",
      desc: "Tuna",
      image: "http://lorempixel.com/640/480/nature",
    },
    {
      id: "12",
      name: "Handmade Fresh Pants",
      price: "574.00",
      desc: "Chicken",
      image: "http://lorempixel.com/640/480/sports",
    },
    {
      id: "13",
      name: "Generic Wooden Shoes",
      price: "780.00",
      desc: "Pizza",
      image: "http://lorempixel.com/640/480/fashion",
    },
    {
      id: "14",
      name: "Handcrafted Concrete Pizza",
      price: "447.00",
      desc: "Hat",
      image: "http://lorempixel.com/640/480/fashion",
    },
    {
      id: "15",
      name: "Generic Fresh Pizza",
      price: "231.00",
      desc: "Chicken",
      image: "http://lorempixel.com/640/480/fashion",
    },
    {
      id: "16",
      name: "Practical Granite Cheese",
      price: "883.00",
      desc: "Chicken",
      image: "http://lorempixel.com/640/480/nature",
    },
    {
      id: "17",
      name: "Incredible Plastic Hat",
      price: "100.00",
      desc: "Tuna",
      image: "http://lorempixel.com/640/480/technics",
    },
    {
      id: "18",
      name: "Generic Soft Bike",
      price: "167.00",
      desc: "Table",
      image: "http://lorempixel.com/640/480/cats",
    },
    {
      id: "19",
      name: "Incredible Granite Mouse",
      price: "421.00",
      desc: "Shirt",
      image: "http://lorempixel.com/640/480/food",
    },
    {
      id: "20",
      name: "Unbranded Granite Hat",
      price: "183.00",
      desc: "Gloves",
      image: "http://lorempixel.com/640/480/city",
    },
    {
      id: "21",
      name: "Ergonomic Fresh Pizza",
      price: "24.00",
      desc: "Bike",
      image: "http://lorempixel.com/640/480/abstract",
    },
    {
      id: "22",
      name: "Fantastic Metal Car",
      price: "734.00",
      desc: "Computer",
      image: "http://lorempixel.com/640/480/transport",
    },
    {
      id: "23",
      name: "Incredible Fresh Tuna",
      price: "63.00",
      desc: "Shirt",
      image: "http://lorempixel.com/640/480/nature",
    },
    {
      id: "24",
      name: "Intelligent Concrete Chicken",
      price: "104.00",
      desc: "Shirt",
      image: "http://lorempixel.com/640/480/transport",
    },
    {
      id: "25",
      name: "Intelligent Plastic Chair",
      price: "833.00",
      desc: "Fish",
      image: "http://lorempixel.com/640/480/sports",
    },
    {
      id: "26",
      name: "Ergonomic Frozen Towels",
      price: "204.00",
      desc: "Pizza",
      image: "http://lorempixel.com/640/480/nature",
    },
    {
      id: "27",
      name: "Unbranded Cotton Cheese",
      price: "731.00",
      desc: "Bike",
      image: "http://lorempixel.com/640/480/nature",
    },
    {
      id: "28",
      name: "Generic Metal Ball",
      price: "309.00",
      desc: "Ball",
      image: "http://lorempixel.com/640/480/city",
    },
    {
      id: "29",
      name: "Tasty Granite Towels",
      price: "955.00",
      desc: "Gloves",
      image: "http://lorempixel.com/640/480/nature",
    },
    {
      id: "30",
      name: "Unbranded Concrete Tuna",
      price: "957.00",
      desc: "Pants",
      image: "http://lorempixel.com/640/480/animals",
    },
    {
      id: "31",
      name: "Intelligent Steel Pizza",
      price: "796.00",
      desc: "Computer",
      image: "http://lorempixel.com/640/480/fashion",
    },
    {
      id: "32",
      name: "Fantastic Metal Soap",
      price: "284.00",
      desc: "Shoes",
      image: "http://lorempixel.com/640/480/nightlife",
    },
    {
      id: "33",
      name: "Small Plastic Ball",
      price: "732.00",
      desc: "Car",
      image: "http://lorempixel.com/640/480/people",
    },
    {
      id: "34",
      name: "Fantastic Steel Table",
      price: "832.00",
      desc: "Chair",
      image: "http://lorempixel.com/640/480/people",
    },
    {
      id: "35",
      name: "Unbranded Wooden Shirt",
      price: "136.00",
      desc: "Salad",
      image: "http://lorempixel.com/640/480/transport",
    },
    {
      id: "36",
      name: "Generic Wooden Soap",
      price: "7.00",
      desc: "Towels",
      image: "http://lorempixel.com/640/480/sports",
    },
    {
      id: "37",
      name: "Tasty Frozen Table",
      price: "3.00",
      desc: "Soap",
      image: "http://lorempixel.com/640/480/technics",
    },
    {
      id: "38",
      name: "Licensed Metal Bacon",
      price: "489.00",
      desc: "Chair",
      image: "http://lorempixel.com/640/480/business",
    },
    {
      id: "39",
      name: "Sleek Wooden Salad",
      price: "141.00",
      desc: "Keyboard",
      image: "http://lorempixel.com/640/480/cats",
    },
    {
      id: "40",
      name: "Licensed Steel Car",
      price: "482.00",
      desc: "Sausages",
      image: "http://lorempixel.com/640/480/business",
    },
    {
      id: "41",
      name: "Unbranded Steel Towels",
      price: "811.00",
      desc: "Shirt",
      image: "http://lorempixel.com/640/480/nature",
    },
    {
      id: "42",
      name: "Practical Plastic Tuna",
      price: "951.00",
      desc: "Bacon",
      image: "http://lorempixel.com/640/480/animals",
    },
    {
      id: "43",
      name: "Licensed Frozen Shirt",
      price: "60.00",
      desc: "Ball",
      image: "http://lorempixel.com/640/480/transport",
    },
    {
      id: "44",
      name: "Unbranded Steel Chair",
      price: "392.00",
      desc: "Chips",
      image: "http://lorempixel.com/640/480/nightlife",
    },
    {
      id: "45",
      name: "Intelligent Wooden Keyboard",
      price: "852.00",
      desc: "Towels",
      image: "http://lorempixel.com/640/480/food",
    },
    {
      id: "46",
      name: "Gorgeous Soft Salad",
      price: "700.00",
      desc: "Hat",
      image: "http://lorempixel.com/640/480/fashion",
    },
    {
      id: "47",
      name: "Practical Concrete Pants",
      price: "809.00",
      desc: "Salad",
      image: "http://lorempixel.com/640/480/people",
    },
    {
      id: "48",
      name: "Licensed Granite Table",
      price: "419.00",
      desc: "Gloves",
      image: "http://lorempixel.com/640/480/abstract",
    },
    {
      id: "49",
      name: "Licensed Soft Soap",
      price: "369.00",
      desc: "Car",
      image: "http://lorempixel.com/640/480/nature",
    },
    {
      id: "50",
      name: "Handmade Soft Sausages",
      price: "468.00",
      desc: "Bacon",
      image: "http://lorempixel.com/640/480/business",
    },
    {
      id: "51",
      name: "Tasty Plastic Cheese",
      price: "394.00",
      desc: "Chips",
      image: "http://lorempixel.com/640/480/fashion",
    },
    {
      id: "52",
      name: "Refined Cotton Mouse",
      price: "289.00",
      desc: "Ball",
      image: "http://lorempixel.com/640/480/food",
    },
    {
      id: "53",
      name: "Intelligent Plastic Tuna",
      price: "212.00",
      desc: "Pants",
      image: "http://lorempixel.com/640/480/sports",
    },
    {
      id: "54",
      name: "Generic Plastic Towels",
      price: "555.00",
      desc: "Pizza",
      image: "http://lorempixel.com/640/480/animals",
    },
    {
      id: "55",
      name: "Awesome Metal Tuna",
      price: "678.00",
      desc: "Sausages",
      image: "http://lorempixel.com/640/480/city",
    },
    {
      id: "56",
      name: "Gorgeous Cotton Hat",
      price: "903.00",
      desc: "Sausages",
      image: "http://lorempixel.com/640/480/nightlife",
    },
    {
      id: "57",
      name: "Gorgeous Wooden Ball",
      price: "521.00",
      desc: "Bacon",
      image: "http://lorempixel.com/640/480/transport",
    },
    {
      id: "58",
      name: "Tasty Fresh Table",
      price: "826.00",
      desc: "Chips",
      image: "http://lorempixel.com/640/480/technics",
    },
    {
      id: "59",
      name: "Practical Soft Soap",
      price: "206.00",
      desc: "Shirt",
      image: "http://lorempixel.com/640/480/nature",
    },
    {
      id: "60",
      name: "Small Soft Table",
      price: "827.00",
      desc: "Keyboard",
      image: "http://lorempixel.com/640/480/food",
    },
    {
      id: "61",
      name: "Gorgeous Concrete Bike",
      price: "698.00",
      desc: "Chicken",
      image: "http://lorempixel.com/640/480/nightlife",
    },
    {
      id: "62",
      name: "Handcrafted Granite Shoes",
      price: "637.00",
      desc: "Computer",
      image: "http://lorempixel.com/640/480/transport",
    },
    {
      id: "63",
      name: "Generic Granite Chips",
      price: "110.00",
      desc: "Car",
      image: "http://lorempixel.com/640/480/sports",
    },
    {
      id: "64",
      name: "Refined Plastic Mouse",
      price: "358.00",
      desc: "Computer",
      image: "http://lorempixel.com/640/480/city",
    },
    {
      id: "65",
      name: "Licensed Fresh Bacon",
      price: "155.00",
      desc: "Computer",
      image: "http://lorempixel.com/640/480/abstract",
    },
    {
      id: "66",
      name: "Generic Rubber Gloves",
      price: "67.00",
      desc: "Fish",
      image: "http://lorempixel.com/640/480/transport",
    },
    {
      id: "67",
      name: "Licensed Cotton Sausages",
      price: "405.00",
      desc: "Keyboard",
      image: "http://lorempixel.com/640/480/food",
    },
    {
      id: "68",
      name: "Licensed Granite Mouse",
      price: "258.00",
      desc: "Sausages",
      image: "http://lorempixel.com/640/480/business",
    },
    {
      id: "69",
      name: "Small Metal Chair",
      price: "484.00",
      desc: "Hat",
      image: "http://lorempixel.com/640/480/sports",
    },
    {
      id: "70",
      name: "Ergonomic Concrete Mouse",
      price: "222.00",
      desc: "Mouse",
      image: "http://lorempixel.com/640/480/business",
    },
    {
      id: "71",
      name: "Sleek Frozen Salad",
      price: "511.00",
      desc: "Chips",
      image: "http://lorempixel.com/640/480/city",
    },
    {
      id: "72",
      name: "Small Metal Table",
      price: "452.00",
      desc: "Fish",
      image: "http://lorempixel.com/640/480/abstract",
    },
    {
      id: "73",
      name: "Handcrafted Metal Chips",
      price: "96.00",
      desc: "Car",
      image: "http://lorempixel.com/640/480/cats",
    },
    {
      id: "74",
      name: "Small Steel Tuna",
      price: "98.00",
      desc: "Soap",
      image: "http://lorempixel.com/640/480/abstract",
    },
    {
      id: "75",
      name: "Practical Granite Fish",
      price: "633.00",
      desc: "Computer",
      image: "http://lorempixel.com/640/480/abstract",
    },
    {
      id: "76",
      name: "Refined Frozen Towels",
      price: "242.00",
      desc: "Table",
      image: "http://lorempixel.com/640/480/cats",
    },
    {
      id: "77",
      name: "Tasty Cotton Mouse",
      price: "377.00",
      desc: "Fish",
      image: "http://lorempixel.com/640/480/sports",
    },
    {
      id: "78",
      name: "Practical Concrete Chicken",
      price: "810.00",
      desc: "Computer",
      image: "http://lorempixel.com/640/480/animals",
    },
    {
      id: "79",
      name: "Fantastic Cotton Pants",
      price: "624.00",
      desc: "Fish",
      image: "http://lorempixel.com/640/480/nature",
    },
    {
      id: "80",
      name: "Handcrafted Soft Car",
      price: "701.00",
      desc: "Fish",
      image: "http://lorempixel.com/640/480/cats",
    },
    {
      id: "81",
      name: "Rustic Concrete Pizza",
      price: "410.00",
      desc: "Fish",
      image: "http://lorempixel.com/640/480/food",
    },
    {
      id: "82",
      name: "Handcrafted Soft Bike",
      price: "174.00",
      desc: "Chicken",
      image: "http://lorempixel.com/640/480/fashion",
    },
    {
      id: "83",
      name: "Refined Steel Computer",
      price: "573.00",
      desc: "Cheese",
      image: "http://lorempixel.com/640/480/abstract",
    },
    {
      id: "84",
      name: "Unbranded Rubber Car",
      price: "328.00",
      desc: "Chair",
      image: "http://lorempixel.com/640/480/sports",
    },
    {
      id: "85",
      name: "Unbranded Metal Towels",
      price: "198.00",
      desc: "Table",
      image: "http://lorempixel.com/640/480/abstract",
    },
    {
      id: "86",
      name: "Ergonomic Soft Fish",
      price: "21.00",
      desc: "Table",
      image: "http://lorempixel.com/640/480/technics",
    },
    {
      id: "87",
      name: "Small Concrete Ball",
      price: "903.00",
      desc: "Hat",
      image: "http://lorempixel.com/640/480/fashion",
    },
    {
      id: "88",
      name: "Awesome Fresh Sausages",
      price: "60.00",
      desc: "Mouse",
      image: "http://lorempixel.com/640/480/technics",
    },
    {
      id: "89",
      name: "Fantastic Frozen Pants",
      price: "453.00",
      desc: "Keyboard",
      image: "http://lorempixel.com/640/480/food",
    },
    {
      id: "90",
      name: "Ergonomic Metal Pants",
      price: "217.00",
      desc: "Shirt",
      image: "http://lorempixel.com/640/480/city",
    },
    {
      id: "91",
      name: "Licensed Soft Gloves",
      price: "86.00",
      desc: "Chicken",
      image: "http://lorempixel.com/640/480/fashion",
    },
    {
      id: "92",
      name: "Sleek Concrete Fish",
      price: "59.00",
      desc: "Bike",
      image: "http://lorempixel.com/640/480/people",
    },
    {
      id: "93",
      name: "Practical Cotton Car",
      price: "82.00",
      desc: "Chair",
      image: "http://lorempixel.com/640/480/fashion",
    },
    {
      id: "94",
      name: "Sleek Wooden Chicken",
      price: "624.00",
      desc: "Keyboard",
      image: "http://lorempixel.com/640/480/business",
    },
    {
      id: "95",
      name: "Licensed Frozen Fish",
      price: "52.00",
      desc: "Towels",
      image: "http://lorempixel.com/640/480/people",
    },
    {
      id: "96",
      name: "Ergonomic Frozen Shoes",
      price: "507.00",
      desc: "Bike",
      image: "http://lorempixel.com/640/480/nightlife",
    },
    {
      id: "97",
      name: "Unbranded Fresh Pants",
      price: "586.00",
      desc: "Shoes",
      image: "http://lorempixel.com/640/480/cats",
    },
    {
      id: "98",
      name: "Practical Wooden Shoes",
      price: "374.00",
      desc: "Computer",
      image: "http://lorempixel.com/640/480/sports",
    },
    {
      id: "99",
      name: "Fantastic Metal Pants",
      price: "586.00",
      desc: "Mouse",
      image: "http://lorempixel.com/640/480/sports",
    },
    {
      id: "100",
      name: "Generic Granite Chicken",
      price: "98.00",
      desc: "Fish",
      image: "http://lorempixel.com/640/480/transport",
    },
  ];
  return (
    <div className="App">
      {arr.map(function (v, i) {
        return <UserCard data={v} />;
      })}
    </div>
  );
}
function UserCard({ data: { price, desc, name, image } }) {
  return (
    <div className="card">
      <img src={image} width="212" />
      <div className="card_desc">
        <h1>{name}</h1>
        <p>{desc}</p>
        <button>{price}</button>
      </div>
    </div>
  );
}
export default App;
